### ISSUE TITLE
Xamarin Android app running out of memory because of an SSL error in ACPCore, if the mobile date is advanced by 5 days.

### ISSUE THREAD

**Issue by tejas-ad** [adobe/xamarin-acpcore#23]
### Expected Behaviour
Application should not run out of memory because of SSL chain validation failure.
### Actual Behaviour
Application runs out of memory.

**Question: Alternatively, can adobe provide a way for the app to handle SSL callbacks on its own?**

#### Steps to Reproduce

1. Configure ACP Core for Xamarin Android with instructions provided in the repo/adobe website.
2. Advance mobile device date by 5 days.
3. Launch the app.
4. Observe logs. It can be seen that the memory footprint of the app keeps increasing. At the end, the app throws out of memory error with the following stack trace

#### Platform and Version
Xamarin.Android v11.0.2.0,  Android OS 9.0

#### Sample Code that illustrates the problem
See code setup instructions provided in the repository.

#### Logs taken while reproducing problem
Stack Trace:

Clamp target GC heap from 280MB to 256MB
Alloc concurrent copying GC freed 0(0B) AllocSpace objects, 0(0B) LOS objects, 0% free, 256MB/256MB, paused 46us total 1.708s
Throwing OutOfMemoryError "Failed to allocate a 32 byte allocation with 0 free bytes and 0B until OOM, max allowed footprint 268435456, growth limit 268435456" (VmSize 4303372 kB, recursive case)
WaitForGcToComplete blocked Alloc on HeapTrim for 4.149s
Starting a blocking GC Alloc
Starting a blocking GC Alloc
Waiting for a blocking GC Alloc
Waiting for a blocking GC Alloc
"pool-3-thread-1" prio=5 tid=37 Runnable
| group="main" sCount=0 dsCount=0 flags=0 obj=0x12c83b40 self=0x7887eed400
| sysTid=26706 nice=0 cgrp=default sched=0/0 handle=0x788598f4f0
| state=R schedstat=( 61680019095 159857227 1889 ) utm=6025 stm=143 core=4 HZ=100
| stack=0x788588c000-0x788588e000 stackSize=1041KB
| held mutexes= "mutator lock"(shared held)
at java.util.Arrays.copyOf(Arrays.java:3164)
at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
at java.io.OutputStream.write(OutputStream.java:75)
at sun.security.util.DerValue.encode(DerValue.java:425)
at sun.security.util.DerValue.toByteArray(DerValue.java:861)
at sun.security.x509.X509CRLEntryImpl.parse(X509CRLEntryImpl.java:456)
at sun.security.x509.X509CRLEntryImpl.<init>(X509CRLEntryImpl.java:133)
at sun.security.x509.X509CRLImpl.parse(X509CRLImpl.java:1161)
at sun.security.x509.X509CRLImpl.<init>(X509CRLImpl.java:146)
at sun.security.provider.X509Factory.intern(X509Factory.java:206)
at sun.security.x509.X509CRLImpl.toImpl(X509CRLImpl.java:1235)
at sun.security.provider.certpath.DistributionPointFetcher.verifyCRL(DistributionPointFetcher.java:331)
at sun.security.provider.certpath.DistributionPointFetcher.getCRLs(DistributionPointFetcher.java:209)
at sun.security.provider.certpath.DistributionPointFetcher.getCRLs(DistributionPointFetcher.java:121)
at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:552)
at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:465)
at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:394)
at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:337)
at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:222)
at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
at sun.security.provider.certpath.DistributionPoi
at com.android.org.conscrypt.DelegatingCertPathValidator.engineValidate(DelegatingCertPathValidator.java:44)
at java.security.cert.CertPathValidator.validate(CertPathValidator.java:301)
at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:715)
at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:543)
at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:564)
at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:609)
at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:422)
at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:343)
at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:208)
at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:426)
at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:231)
at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:1480)
at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:1424)
at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:1368)
at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:219)
at com.andion.java:142)
at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:104)
at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:392)
at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:325)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:470)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:26)
**at com.adobe.mobile.RemoteDownload$DownloadFileTask.run(RemoteDownload.java:387)
at com.adobe.mobile.RemoteDownload.remoteDownloadSync(RemoteDownload.java:61)
at com.adobe.mobile.RemoteDownload.remoteDownloadSync(RemoteDownload.java:71)
at com.adobe.mobile.MobileConfig$8.run(MobileConfig.java:692)**
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)

**Additional Notes:**
After looking at the sample project, I tried to enable the verbose logging for ACPCore but did not get any additional logs from the app. Here is the error stack trace from the sample app. The sample app errored out pretty quickly and hence did not freeze. Not sure what needs to be done differently in the app I am working on:
[AdobeExperienceSDK] HttpConnectionHandler - Connection failure (Chain validation failed)
[AdobeExperienceSDK] AndroidHttpConnection - Could not get response code. (javax.net.ssl.SSLHandshakeException: Chain validation failed)
[chatty] uid=10437(com.adobe.marketing.mobile.acpcoretestapp) pool-6-thread-1 identical 3 lines
[AdobeExperienceSDK] AndroidHttpConnection - Could not get response code. (javax.net.ssl.SSLHandshakeException: Chain validation failed)
[AdobeExperienceSDK] AndroidHttpConnection - Could not get the response message. (javax.net.ssl.SSLHandshakeException: Chain validation failed)
[AdobeExperienceSDK] RemoteDownloader - File could not be downloaded from URL (https://assets.adobedtm.com/launch-ENf8ed5382efc84d5b81a9be8dcc231be1-development.json) Response: (-1) Message: (null)
[AdobeExperienceSDK] AndroidHttpConnection - Could not get the input stream. (javax.net.ssl.SSLHandshakeException: Chain validation failed)
[AdobeExperienceSDK] ConfigurationExtension - Problem while downloading config.
[AdobeExperienceSDK] CacheManager - Cached Files - Directory is empty (/data/user/0/com.adobe.marketing.mobile.acpcoretestapp/cache/adbdownloadcache).
[AdobeExperienceSDK] ConfigurationExtension - Either there was no cached config, or there was a problem loading the cached config.
[AdobeExperienceSDK] ConfigurationExtension - Unable to fetch config. Rolling back to previous configuration.

**Comment by rymorale** [comment]
Hi @tejas-ad,
Based on the logs you provided, it looks like the issue is occurring with the Xamarin wrapper for the V4 Mobile SDK. Could you share the version of the Mobile SDK that you are using? 
The reason that the issue does not occur with the ACPCore sample project is that it is a wrapper for the V5 Mobile SDK. Would you be able to use the V5 Mobile SDK wrapper instead as it resolves your issue? The V5 ACPCore package can be added to your project via NuGet: https://www.nuget.org/packages/Adobe.ACPCore.Android/

Please let me know if you have any additional questions.

Thanks,
Ryan

**Comment by tejas-ad** [comment]
Thank you for the response, @rymorale! We recently made to move to ACPCore and it looks like I included the stack trace from the V4 version of the code, as I was testing both versions out. We are seeing the same issue on ACPCore as well. Here is the stack trace for the same issue from our project after integrating ACPCore:

Clamp target GC heap from 279MB to 256MB
Alloc concurrent copying GC freed 0(0B) AllocSpace objects, 0(0B) LOS objects, 0% free, 255MB/256MB, paused 51us total 1.711s
Throwing OutOfMemoryError "Failed to allocate a 152 byte allocation with 72 free bytes and 72B until OOM, max allowed footprint 268435456, growth limit 268435456" (VmSize 4360856 kB, recursive case)
WaitForGcToComplete blocked HeapTrim on HeapTrim for 10.489s
Waiting for a blocking GC Alloc
"pool-18-thread-1" prio=5 tid=52 Runnable
  | group="main" sCount=0 dsCount=0 flags=0 obj=0x12c83fb8 self=0x78844de800
  | sysTid=28394 nice=0 cgrp=default sched=0/0 handle=0x7883ee14f0
  | state=R schedstat=( 75217582411 298974834 3298 ) utm=7299 stm=222 core=4 HZ=100
  | stack=0x7883dde000-0x7883de0000 stackSize=1041KB
  | held mutexes= "mutator lock"(shared held)
  at java.util.Arrays.copyOf(Arrays.java:3164)
  at java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:191)
  at sun.security.util.DerValue.toByteArray(DerValue.java:863)
  at sun.security.x509.X509CRLEntryImpl.parse(X509CRLEntryImpl.java:456)
  at sun.security.x509.X509CRLEntryImpl.<init>(X509CRLEntryImpl.java:133)
  at sun.security.x509.X509CRLImpl.parse(X509CRLImpl.java:1161)
  at sun.security.x509.X509CRLImpl.<init>(X509CRLImpl.java:146)
  at sun.security.provider.X509Factory.intern(X509Factory.java:206)
  at sun.security.x509.X509CRLImpl.toImpl(X509CRLImpl.java:1235)
  at sun.security.provider.certpath.AlgorithmChecker.check(AlgorithmChecker.java:396)
  at sun.security.provider.certpath.DistributionPointFetcher.verifyCRL(DistributionPointFetcher.java:667)
  at sun.security.provider.certpath.DistributionPointFetcher.getCRLs(DistributionPointFetcher.java:209)
  at sun.security.provider.certpath.DistributionPointFetcher.getCRLs(DistributionPointFetcher.java:121)
  at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:552)
  at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:465)
  at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:394)
  at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:337)
  at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
  at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:222)
  at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
  at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
  at com.android.org.conscrypt.DelegatingCertPathValidator.engineValidate(DelegatingCertPathValidator.java:44)
  at java.security.cert.CertPathValidator.validate(CertPathValidator.java:301)
  at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:715)
  at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:543)
  at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:564)
  at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:609)
  at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:499)
  at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:422)
  at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:343)
  at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
  at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
  at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:208)
  at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:426)
  at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native method)
  at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:383)
  at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:231)
  at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:1480)
  at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:1424)
  at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:1368)
  at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:219)
  at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:142)
  at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:104)
  at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:392)
  at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:325)
  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:470)
  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
  at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
  at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:26)
  at com.adobe.marketing.mobile.HttpConnectionHandler.connect(HttpConnectionHandler.java:210)
  at com.adobe.marketing.mobile.AndroidNetworkService.doConnection(AndroidNetworkService.java:166)
  at com.adobe.marketing.mobile.AndroidNetworkService.connectUrl(AndroidNetworkService.java:78)
  at com.adobe.marketing.mobile.RemoteDownloader.startDownloadSync(RemoteDownloader.java:264)
  at com.adobe.marketing.mobile.ConfigurationDownloader.downloadConfig(ConfigurationDownloader.java:62)
  at com.adobe.marketing.mobile.ConfigurationExtension.processConfigureWithAppIDEvent(ConfigurationExtension.java:447)
  at com.adobe.marketing.mobile.ConfigurationExtension$3.run(ConfigurationExtension.java:305)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  at java.lang.Thread.run(Thread.java:764)

**Comment by rymorale** [comment]
Thanks for the info. Have you been able to try a different android device / simulator? If not, could you please give that a try?

As you mentioned in your first comment, the issue doesn't occur when testing with the sample app included with the ACPCore solution. I've been trying to reproduce the issue locally and have had no luck. Did you happen to change any project options for your app? Additionally, it would be helpful if you could provide a simple project which can reproduce the issue. In the meantime, I will continue to test it on my end.

Thanks,
Ryan

**Comment by tejas-ad** [comment]
The issue is reproducible on some android phones, not all. The code is running fine on a Samsung Galaxy S7 with Android 7. However, on a Samsung Galaxy S8 with Android 9, the issue is consistently reproducible.

I tried to match the project build settings (most of the settings were the same anyway) but that did not change anything. I also tried matching the timeouts in the configurations but that did not help either(e.g. the configuration for the sample app is at: https://assets.adobedtm.com/launch-ENf8ed5382efc84d5b81a9be8dcc231be1-development.json). I will try to create a sample project and see if the issue can be reproduced in that.

Thanks,
Tejas.

**Comment by rymorale** [comment]
Thanks for the update @tejas-ad. We will continue to investigate the issue and will let you know if we have any updates.

**Comment by shalehaha** [comment]
@tejas-ad 
Is your app live? We tried to reproduce it using a test app on an Galaxy 8 with Android 9, but no luck. So wondering if there is any way we can test it with your app.

**Comment by tejas-ad** [comment]
Apologies for the delay in responding. We traced the issue to the configuration download and went with offline configuration using ADBMobileConfig.json. The issue itself turned out to be an okhttp/android/conscrypt issue (https://github.com/google/conscrypt/issues/520) and we plan to add our steps/observations to that existing issue on conscrypt. Thank you for the support!

**Comment by shalehaha** [comment]
@tejas-ad 
Thanks, this is quite helpful. We have an SSL certificate that is using a large CRL, which might be the reason for this crash. Right now we are working with another internal team to check whether it is possible to switch to use a small CRL. Will keep you updated.

Also, our SDK does allow you to override the network stack if you want, checkout it out at https://aep-sdks.gitbook.io/docs/foundation-extensions/mobile-core/platform-services.

**Comment by tejas-ad** [comment]
@shalehaha Thanks a lot for that information on the facility to override network stack. We may end up using it in one of our future releases. And yes, do let us know if the switch to a smaller CRL eventually happens. If you don't have any concerns, we can mark this issue as closed.
